"""empty message

Revision ID: 28401d063ca8
Revises: 00b7a546e4d5
Create Date: 2025-08-22 11:13:52.331354

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '28401d063ca8'
down_revision = '00b7a546e4d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.alter_column('state',
               existing_type=postgresql.ENUM('TODO', 'IN_PROGRESS', 'DONE', name='state'),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.alter_column('state',
               existing_type=sa.String(length=255),
               type_=postgresql.ENUM('TODO', 'IN_PROGRESS', 'DONE', name='state'),
               existing_nullable=False)

    # ### end Alembic commands ###
