"""Agregar tabla de favoritos

Revision ID: 3386cfac014f
Revises: ab295d310b75
Create Date: 2025-08-13 12:31:24.888866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3386cfac014f'
down_revision = 'ab295d310b75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_boards',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('board_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'board_id')
    )
    op.drop_table('usuarios')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image', sa.VARCHAR(length=500), autoincrement=False, nullable=True))

    op.create_table('usuarios',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=70), autoincrement=False, nullable=False),
    sa.Column('apellido', sa.VARCHAR(length=70), autoincrement=False, nullable=False),
    sa.Column('correo', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('contrasena_hashada', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('usuarios_pkey')),
    sa.UniqueConstraint('correo', name=op.f('usuarios_correo_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('favorite_boards')
    # ### end Alembic commands ###
