"""Initial migration

Revision ID: 5a003ece2801
Revises: 8ce8fa8163a5
Create Date: 2025-07-23 00:39:55.919739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a003ece2801'
down_revision = '8ce8fa8163a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_image')

    op.create_table('usuarios',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=70), autoincrement=False, nullable=False),
    sa.Column('apellido', sa.VARCHAR(length=70), autoincrement=False, nullable=False),
    sa.Column('correo', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('contrasena_hashada', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('usuarios_pkey')),
    sa.UniqueConstraint('correo', name=op.f('usuarios_correo_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
