"""add lists model

Revision ID: ba2190fe317b
Revises: 78868eb42e3c
Create Date: 2025-09-17 14:53:59.048164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba2190fe317b'
down_revision = '78868eb42e3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('board_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lists_board_id'), ['board_id'], unique=False)
        batch_op.create_index('uq_lists_board_lower_name', ['board_id', sa.literal_column('LOWER(name)')], unique=True)

    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('list_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_cards_list_id'), ['list_id'], unique=False)
        batch_op.create_foreign_key(None, 'lists', ['list_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_cards_list_id'))
        batch_op.drop_column('list_id')

    with op.batch_alter_table('lists', schema=None) as batch_op:
        batch_op.drop_index('uq_lists_board_lower_name')
        batch_op.drop_index(batch_op.f('ix_lists_board_id'))

    op.drop_table('lists')
    # ### end Alembic commands ###
